// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loezrjmwjsrbvudltfzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvZXpyam13anNyYnZ1ZGx0ZnpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODI2MjEsImV4cCI6MjA3MTk1ODYyMX0.tiFv7sh8JNOsKjxhn4LAO9SAyLheqwC1FUDNqVPhFHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});